name: dl_datamine
description: Dart CLI tool for downloading and pre-processing Dragalia Lost game assets.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  http: ^0.13.3
  uuid: ^3.0.4
  image: ^3.0.4

dev_dependencies:
  pedantic: ^1.11.1
